services:
    server:
        extends:
            file: ./docker-compose.test.yml
            service: server
        build: 
            args:
                - NODE_ENV=development
        command: ["yarn", "debug"]
        volumes:
            - .:/app
        environment:
            - NPM_TOKEN
    mongo:
        image: mongo
    redis:
        image: redis
secrets:
    YARN_TOKEN:
        environment: NPM_TOKEN